CREATE TABLE [dbo].[TST] (
    [ID]   INT          NULL,
    [NOME] VARCHAR (50) NULL
);


GO
CREATE TRIGGER TRG_TST_LOG ON TST
FOR INSERT
AS
INSERT INTO TB_TST_LOG 
SELECT *, GETDATE() FROM INSERTED
